language: node_js
node_js:
- "node"

before_install:
  - sudo apt-get install -y r-recommended
addons:
  apt:
    update: true

cache:
  directories:
  - "node_modules"

script:
  - npm run check-markdown
  - npm run check-html
  - npm run check-links -- https://jrnold.github.io/r4ds-exercise-solutions
