language: R
pandoc: 2.5

cache:
  packages: true
  directories:
  - "_build"
  -  "_bookdown_files"

addons:
  apt:
    packages:
      - libxml2-dev

script:
  - Rscript ./bin/render.R --force all

deploy:
  provider: pages
  local-dir: "_build"
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  on:
    branch: master

notifications:
  email: false

