language: R
pandoc: 2.5

cache:
  packages: true
  directories:
  - "_build"

addons:
  apt:
    packages:
      - libxml2-dev

script:
  - Rscript -e 'bookdown::render_book("index.rmd")'

notifications:
  email: false
