language: node_js
node_js:
- "node"

cache:
  directories:
  - "node_modules"

script:
  - npm run check-markdown
  - npm run check-html
  - npm run check-links -- https://jrnold.github.io/r4ds-exercise-solutions
